### PR TITLE
Preprocessor mode fixes

### LINKED ISSUE #175: export "C" fails through c2nimport()
Minimal example:
```nim
import nimterop / cimport
c2nImport("hello.h")
```
```c
#ifdef __cplusplus
extern "C" {
#endif
  struct Foo {
    int x;
  };
#ifdef __cplusplus
}
#endif
```
```
(1, 11) Error: identifier expected, but got: C
```
c2nim is supposed to handle `__cplusplus` (and thus strip out `extern "C"`) by default: the flaw I think is in `toast` doing the preproc pass when called through `c2nimport()`, seen [here](https://github.com/nimterop/nimterop/blob/master/nimterop/cimport.nim#L133).

### PR DESCRIPTION
**Pull request by awr1**
Fixes #175

### CODE REVIEW

File: nimterop/toast.nim [hunk 1]
```diff
@@ -9,15 +9,18 @@ proc process(gState: State, path: string, astTable: AstTable) =
...
+    file = path.splitFile()
 
   defer:
     parser.tsParserDelete()
 
   if gState.mode.Bl:
-    if ext in [".h", ".c"]:
+    if '.' in file.name:
+      # triage for autoconf (e.g. '.h.in') until stdlib fix
+      file = file.name.splitFile()
```
Comment (genotrance) [inline nimterop/toast.nim:20]: This is better handled by the wrapper dev - they can use cpFile or mvFile to copy/rename the source file to something else, if they want to use the file raw.

Better yet, they should be using getHeader() to build the library which will generate the final .h files appropriate to the target platform. See nimarchive wrapper for an example of this.

**Comment by genotrance** [comment]
I'm good with most changes, had one comment on h.in which we should avoid.

Further, will be awesome if PR could also fix mode = "c" or "cpp" instances in build.nim.

File: nimterop/getters.nim [hunk 2]
```diff
@@ -695,3 +694,16 @@ proc expandSymlinkAbs*(path: string): string =
...
+  if file.ext in [".hxx", ".hpp", ".hh", ".H", ".h++", ".cpp", ".cxx", ".cc", ".C", ".c++"]:
+    result = "cpp"
+  else:
+    result = "c"
+
+proc xModeArg(mode: string) :string =
+  if mode == "cpp":
+    result = "-xc++"
+  elif mode == "c":
+    result = "-xc"
```
Comment (genotrance) [inline nimterop/getters.nim:709]: Nitpick - getCompilerMode, getModeArg to keep with the getX theme.

File: nimterop/getters.nim [hunk 3]
```diff
@@ -695,3 +694,16 @@ proc expandSymlinkAbs*(path: string): string =
     result = path.expandSymlink().absolutePath(path.parentDir()).normalizedPath()
   except:
     result = path
+
+proc determineCompilerMode(path: string) :string =
+  let file = path.splitFile()
+  if file.ext in [".hxx", ".hpp", ".hh", ".H", ".h++", ".cpp", ".cxx", ".cc", ".C", ".c++"]:
+    result = "cpp"
+  else:
+    result = "c"
```
Comment (genotrance) [inline nimterop/getters.nim:703]: So we are defaulting to C mode if not C++ files? No more complaining if unsupported filetype?

File: nimterop/build.nim [hunk 4]
```diff
@@ -1005,9 +1004,9 @@ macro getHeader*(header: static[string], giturl: static[string] = "", dlurl: sta
 
       # Look in standard path if requested by user
       stdPath =
-        when `nameStd`: getStdPath(`header`) else: ""
+        when `nameStd`: getStdPath(`header`, mode) else: ""
       stdLPath =
-        when `nameStd`: getStdLibPath(`lname`) else: ""
+        when `nameStd`: getStdLibPath(`lname`, mode) else: ""
```
Comment (genotrance) [inline nimterop/build.nim:1010]: Will likely need `mode`.

File: nimterop/cimport.nim [hunk 5]
```diff
@@ -161,6 +161,7 @@ proc getToast(fullpath: string, recurse: bool = false, dynlib: string = "",
   cmd.add &" {fullpath.sanitizePath}"
 
   # see https://github.com/nimterop/nimterop/issues/69
+  echo(cmd)
```
Comment (genotrance) [inline nimterop/cimport.nim:164]: Spurious

File: nimterop/getters.nim (hunk 3 above)
Comment (awr1) [reply nimterop/getters.nim:703]: I think that makes the most sense, considering the test in PCRE: https://github.com/nimterop/nimterop/blob/master/tests/tpcre.nim

Comment (awr1) [reply nimterop/getters.nim:703]: Either that or that test should be changed, and maybe we could raise an exception for unsupported filetypes

Comment (genotrance) [reply nimterop/getters.nim:703]: In that case, tpcre.nim should specify the `-mc` flag in cImport so that the mode is explicit. It might break some wrappers out there but I think it is better to be explicit.

**Comment by genotrance** [comment]
Am actively working on fixing the Windows CI, will notify you when it is functional so that you can test your changes after rebase.

**Comment by awr1** [comment]
Branching off from this, something I remembered is that c2nim[ has its own preprocessor directives](https://github.com/nim-lang/c2nim/blob/master/doc/c2nim.rst#preprocessor-support) for controlling and handling its output, which users typically paste to the top of the header (or make a new header that includes the original library) however, these special directives will error out by the C compiler when performing the `-E -dD` flag, which is not good.

My suggestion: what if `c2nImport()` took in an optional "preface" `static[string]` parameter, which would be pasted on top after the initial preprocessor pass?

**Comment by genotrance** [comment]
Merging - I'd really prefer to split out cimport/build which are compile time compared to toast eventually. Getters was supposed to be the common code but it has grown large as well.

> My suggestion: what if c2nImport() took in an optional "preface" static[string] parameter, which would be pasted on top after the initial preprocessor pass?

Can you please open a separate issue to discuss this?

**Comment by genotrance** [comment]
Main concern with this fix is that it could break existing wrappers since we always ended up using cpp mode by default. Let's hope we don't see any regressions around that.
