### PR TITLE
Make getHeader specify which make strategy to use

### LINKED ISSUE #200: [Feature] Ability to specify make/configure or cmake in getHeader
The current setup of using Cmake over make/configure works fairly well for most cases.

However, for SDL2 there are cmake files that do a much less competent job at building shared/static libs. They mostly work on Mac, but fail on Windows/Linux.

Just an enum in `getHeader` specifying which type to use would be amazing. And it could just default to Cmake to keep the current behaviour

### PR DESCRIPTION
**Pull request by jyapayne**
This is useful for libraries that have either a bad configure/make but a good Cmake or vice versa. 

Fixes #200

### CODE REVIEW

**Comment by jyapayne** [comment]
The travis builds that failed look weird to me. Maybe unrelated failures?

File: nimterop/build.nim [hunk 1]
```diff
@@ -4,6 +4,15 @@ import os except findExe, sleep
 
 import regex
 
+type
+  MakeType* = enum
+    mtConfMake, mtCMake
```
Comment (genotrance) [inline nimterop/build.nim:9]: How about calling this `BuildType` and the options `autoconf` and `cmake`?

File: nimterop/build.nim [hunk 2]
```diff
@@ -806,36 +802,59 @@ proc buildLibrary(lname, outdir, conFlags, cmakeFlags, makeFlags: string): strin
...
+    result.buildPath = outdir
 
-    if not cmakeDeps:
-      if findExe("bash").len != 0:
-        for file in @["configure", "configure.ac", "configure.in", "autogen.sh", "build/autogen.sh"]:
-          if fileExists(outdir / file):
-            configure(outdir, "Makefile", conFlags)
-            conDeps = true
+proc buildLibrary(lname, outdir, conFlags, cmakeFlags, makeFlags: string, preferredMakeType: MakeType): string =
+  var
```
Comment (genotrance) [inline nimterop/build.nim:828]: `buildType = cmake` to make cmake the default if available.

File: nimterop/build.nim [hunk 3]
```diff
@@ -806,36 +802,59 @@ proc buildLibrary(lname, outdir, conFlags, cmakeFlags, makeFlags: string): strin
...
+  case preferredMakeType
+  of mtCMake:
+    buildStatus = buildWithCmake(makePath, cmakeFlags)
+    if not buildStatus.built:
+      buildStatus = buildWithConfMake(makePath, conFlags)
+  of mtConfMake:
+    buildStatus = buildWithConfMake(makePath, conFlags)
+    if not buildStatus.built:
+      buildStatus = buildWithCmake(makePath, cmakeFlags)
+
```
Comment (genotrance) [inline nimterop/build.nim:848]: Works for now but once we add Ninja, premake or something else, this will become too complicated. Any thoughts on how to make this simpler?

File: nimterop/build.nim [hunk 4]
```diff
@@ -806,36 +802,59 @@ proc buildLibrary(lname, outdir, conFlags, cmakeFlags, makeFlags: string): strin
...
+  if buildStatus.buildPath.len > 0:
+    buildStatus.built = findFile(lname, buildStatus.buildPath, regex = true).len > 0
+
+    if not buildStatus.built and fileExists(buildStatus.buildPath / "Makefile"):
```
Comment (genotrance) [inline nimterop/build.nim:852]: This means that if configure or cmake is run, make will not be called. But it needs to be called. See line 807.

File: nimterop/build.nim [hunk 5]
```diff
@@ -903,7 +922,7 @@ macro isDefined*(def: untyped): untyped =
 
 macro getHeader*(header: static[string], giturl: static[string] = "", dlurl: static[string] = "", outdir: static[string] = "",
   conFlags: static[string] = "", cmakeFlags: static[string] = "", makeFlags: static[string] = "",
-  altNames: static[string] = ""): untyped =
+  altNames: static[string] = "", preferredMakeType: static[MakeType] = mtCMake): untyped =
```
Comment (genotrance) [inline nimterop/build.nim:925]: `buildType` instead of `preferredMakeType`.

File: nimterop/build.nim (hunk 4 above)
Comment (jyapayne) [reply nimterop/build.nim:852]: No, it actually will be called because of the line above. But it's probably clearer if I add a different variable here instead of reusing buildStatus.built

File: nimterop/build.nim (hunk 1 above)
Comment (jyapayne) [reply nimterop/build.nim:9]: 👍

File: nimterop/build.nim (hunk 3 above)
Comment (jyapayne) [reply nimterop/build.nim:848]: Need some sort of cascading ruleset. Maybe using an array of priorities, like [btCmake, btAutoconf]

File: nimterop/build.nim (hunk 1 above)
Comment (jyapayne) [reply nimterop/build.nim]: Can't use `cmake` because it conflicts with proc names. Named it `btAutoconf` and `btCmake`

File: nimterop/build.nim (hunk 3 above)
Comment (jyapayne) [reply nimterop/build.nim:847]: I implemented this cascading build type list. It should make adding additional build types much easier.
