### PR TITLE
Fix exprparser pointer issue and test

### LINKED ISSUE #203: Issue with pointers in exprparser
```c
#define STREAMPROC_DUMMY               (STREAMPROC*)0
```
Outputs
```nim
const
  STREAMPROC_DUMMY* = cast[STREAMPROC*](0)
```
Should generate
```nim
const
  STREAMPROC_DUMMY* = cast[ptr STREAMPROC](0)
```

cc: @jyapayne

### PR DESCRIPTION
**Pull request by jyapayne**
Fixes #203 

Note that this only fixes the pointer issue, but not the code reordering, which should be a separate issue.

### CODE REVIEW

File: nimterop/exprparser.nim [hunk 1]
```diff
@@ -548,7 +548,15 @@ proc processTSNode(gState: State, node: TSNode, typeofNode: var PNode): PNode =
     # Input -> true, false
     # Output -> true, false
     result = gState.parseString(node.val)
-  of "type_descriptor", "sized_type_specifier":
+  of "type_descriptor":
+    let pointerDecl = node.anyChildInTree("abstract_pointer_declarator")
```
Comment (genotrance) [inline nimterop/exprparser.nim:552]: This could be any number of pointers, need to count them and generate code accordingly. See how pointers are handled in ast2, can use the same strategy here too, perhaps reuse the code as well.

**Comment by jyapayne** [comment]
@genotrance Should be good to review again. I added the multiple pointer support and fixed the rsa tests

**Comment by genotrance** [comment]
I don't see anything related to rsa tests, do you mean tast2.nim? Looks good otherwise.

**Comment by jyapayne** [comment]
No, the rsa tests were failing on Linux. I added to [this line](https://github.com/nimterop/nimterop/pull/204/files#diff-46f93652319a70da1802d9944e54fb5eR109), which skips an invalid type in the const section.

**Comment by genotrance** [comment]
Okay, wasn't obvious, merging.
